spring:
  application:
    name: Askify
  data:
    mongodb:
      uri: "Your mongodb url"
      auto-index-creation: true
server:
  error:
    include-message: always
    include-binding-errors: always   